title: José Mercado
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.6574468
favicon: null
name: José Mercado
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  saturation: 0.75
  brandColors:
    - '#ffffff'
    - '#cecfd3'
    - '#645f5c'
    - '#010100'
    - '#908b88'
  lightness: 1
  rhythmicContrast: 0.25
typography_spectrum: 0.50931
