name: José Mercado
favicon: null
layout_spectrum: 0.36766506638377905
typography_spectrum: 0.27371349837630987
title: José Mercado
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cecfd3'
    - '#645f5c'
    - '#010100'
    - '#908b88'
  brandStrength: 1
  lightness: 0.057023187167942524
  saturation: 0.14452890655957162
  rhythmicContrast: 0.756612426834181
purpose: []
