name: José Mercado
favicon: null
layout_spectrum: 0.75628
typography_spectrum: 0.18593
title: José Mercado
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2867b4'
    - '#7c8ba0'
    - '#10141d'
    - '#3d3c3a'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
