name: José Mercado
favicon: null
layout_spectrum: 0.25932
typography_spectrum: 0.50931
title: José Mercado
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cecfd3'
    - '#645f5c'
    - '#010100'
    - '#908b88'
  brandStrength: 1
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
